#!/bin/bash
read -p " Enter a number " num1
read -p " Enter second number " num2
if [ $num1 -gt 100 ] ||[  $num1 -lt 0 ]
then 
	echo "numbers out of range (0 to 100)"
	exit
fi
if [ $num2 -gt 100 ] || [ $num2 -lt 0 ]
then 
	echo "numbers out of range (0 to 100)"
	exit
fi

echo " sum of $num1 and $num2 is $(( $num1 + $num2)) "
echo " product of $num1 and $num2 is $((num1 * $num2)) "
